name: loki-builder/frontend
type: module
scripts:
  start: vite
  dev: vite
  build: vite build
  serve: vite preview
dependencies:
  '@ark-ui/solid': ^4.5.1
  '@tauri-apps/api': ^2.1.1
  '@tauri-apps/plugin-os': ~2
  solid-js: ^1.9.3
devDependencies:
  '@babel/preset-typescript': ^7.26.0
  '@catppuccin/palette': ^1.7.1
  '@linaria/core': ^6.2.0
  '@stylistic/eslint-plugin': ^2.11.0
  '@types/node': ^22.9.3
  '@typescript-eslint/eslint-plugin': ^8.15.0
  '@typescript-eslint/parser': ^8.15.0
  '@wyw-in-js/vite': ^0.5.5
  eslint: ^8.57.1
  eslint-plugin-solid: ^0.14.4
  lucide-solid: ^0.460.0
  sass-embedded: ^1.83.0
  typescript: ^5.7.2
  typescript-eslint: ^8.15.0
  vite: ^5.4.11
  vite-plugin-solid: ^2.10.2
