name: loki-builder/frontend
type: module
scripts:
  build: vite build
  dev: vite
  lint: pnpm lint:css && pnpm lint:ts
  lint:css: stylelint "**/*.{css,scss,ts,tsx}"
  lint:ts: eslint .
  serve: vite preview
  start: vite
dependencies:
  '@ark-ui/solid': ^4.10.2
  '@catppuccin/palette': ^1.7.1
  '@solidjs/router': ^0.15.3
  '@tauri-apps/api': ^2.4.1
  '@tauri-apps/plugin-os': ~2.2.1
  lucide-solid: ^0.475.0
  solid-js: ^1.9.5
devDependencies:
  '@acab/ecsstatic': ^0.9.0
  '@babel/preset-typescript': ^7.27.0
  '@linaria/core': ^6.3.0
  '@styled/typescript-styled-plugin': ^1.0.1
  '@stylelint/postcss-css-in-js': ^0.38.0
  '@stylistic/eslint-plugin': ^4.2.0
  '@types/node': ^22.14.0
  '@typescript-eslint/eslint-plugin': ^8.29.1
  '@typescript-eslint/parser': ^8.29.1
  '@wyw-in-js/vite': ^0.5.5
  eslint: ^9.24.0
  eslint-plugin-solid: ^0.14.5
  sass-embedded: ^1.86.3
  stylelint: ^16.18.0
  stylelint-config-standard: ^37.0.0
  stylelint-config-standard-scss: ^14.0.0
  typescript: ^5.8.3
  typescript-eslint: ^8.29.1
  vite: ^6.2.6
  vite-plugin-solid: ^2.11.6
