type: module
scripts:
  start: vite
  dev: vite
  build: vite build
  serve: vite preview
dependencies:
  '@tauri-apps/api': ^2
  '@tauri-apps/plugin-shell': ^2
  solid-js: ^1.7.8
devDependencies:
  concurrently: ^9.1.0
  typescript: ^5.2.2
  vite: ^5.3.1
  vite-plugin-solid: ^2.8.0
