name: loki-builder/frontend
type: module
scripts:
  start: vite
  dev: vite
  build: vite build
  serve: vite preview
  lint: pnpm lint:css && pnpm lint:ts
  lint:css: stylelint "**/*.{css,scss,ts,tsx}"
  lint:ts: eslint .
dependencies:
  '@ark-ui/solid': ^4.10.1
  '@catppuccin/palette': ^1.7.1
  '@solidjs/router': ^0.15.3
  '@tauri-apps/api': ^2.2.0
  '@tauri-apps/plugin-os': ~2.2.0
  lucide-solid: ^0.475.0
  solid-js: ^1.9.4
devDependencies:
  '@babel/preset-typescript': ^7.26.0
  '@linaria/core': ^6.2.0
  '@stylelint/postcss-css-in-js': ^0.38.0
  '@stylistic/eslint-plugin': ^4.0.1
  '@types/node': ^22.13.4
  '@typescript-eslint/eslint-plugin': ^8.24.1
  '@typescript-eslint/parser': ^8.24.1
  '@wyw-in-js/vite': ^0.5.5
  eslint: ^9.20.1
  eslint-plugin-solid: ^0.14.5
  sass-embedded: ^1.85.0
  stylelint: ^16.14.1
  stylelint-config-standard: ^37.0.0
  stylelint-config-standard-scss: ^14.0.0
  typescript: ^5.7.3
  typescript-eslint: ^8.24.1
  vite: ^6.1.1
  vite-plugin-solid: ^2.11.2
