name: loki-builder/frontend
type: module
scripts:
  start: vite
  dev: vite
  build: vite build
  serve: vite preview
dependencies:
  '@tauri-apps/api': ^2.1.1
  '@tauri-apps/plugin-shell': ^2.0.1
  solid-js: ^1.9.3
devDependencies:
  '@stylistic/eslint-plugin': ^2.11.0
  '@typescript-eslint/eslint-plugin': ^8.15.0
  '@typescript-eslint/parser': ^8.15.0
  concurrently: ^9.1.0
  eslint: ^8.57.1
  sass: ^1.81.0
  typescript: ^5.7.2
  vite: ^5.4.11
  vite-plugin-solid: ^2.10.2
